### ISSUE TITLE
app crash on android

### ISSUE THREAD

**Issue by cbanwell** [Wizcorp/WebViewForUnity3D#2]
Hi, running the demo on android I get the following in the adb trace

Call WebView
03-08 11:35:04.669 29759 29796 I Unity   :
03-08 11:35:04.669 29759 29796 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
03-08 11:35:04.669 29759 29796 I Unity   :
03-08 11:35:04.698 29759 29796 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='OpenWebView' signature='(Ljava/lang/String;)V' in class Lcom.unity3d.player.UnityPlayerActivity;
03-08 11:35:04.698 29759 29796 E Unity   : java.lang.NoSuchMethodError: no non-static method with name='OpenWebView' signature='(Ljava/lang/String;)V' in class Lcom.unity3d.player.UnityPlayerActivity;
03-08 11:35:04.698 29759 29796 E Unity   :      at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)
03-08 11:35:04.698 29759 29796 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
03-08 11:35:04.698 29759 29796 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
03-08 11:35:04.698 29759 29796 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
03-08 11:35:04.698 29759 29796 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:394)
03-08 11:35:04.698 29759 29796 E Unity   :      at android.os.Looper.loop(Looper.java:142)
03-08 11:35:04.698 29759 29796 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
03-08 11:35:04.698 29759 29796 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in <303b1ed396ed420184be31eb8dc21cdb>:0
03-08 11:35:04.698 29759 29796 E Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass

**Comment by cbanwell** [comment]
ok, my bad, I didn't include the android manifest :(
